name: CI/CD - Teste e Deploy

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Etapa de Testes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar Pytest
        run: pip install pytest

      - name: Executar testes
        run: pytest -v

  deploy:
    name: Etapa de Deploy (só roda se os testes passarem)
    runs-on: ubuntu-latest

    needs: test
    if: success()

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
